name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    # Revisa el código del repositorio
    - uses: actions/checkout@v4

    # Configura Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Instala las dependencias necesarias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pytest-cov

    # Analiza el código con pylint, ignorando archivos específicos
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --ignore=test.py

    # Ejecuta los tests con unittest
    - name: Run tests with unittest
      run: |
        python -m unittest discover

    # Ejecuta los tests con pytest y muestra la cobertura
    - name: Run tests and show coverage
      run: |
        pytest --cov=. --cov-report=term-missing || true
